name: fabrikod_quran
description: The Holy Qur'an App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Localications
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  #State Managements
  provider: ^6.0.3                                        # Provide state management

  #Network
  http: ^0.13.5
  html: ^0.15.1

  # Google
  google_fonts: ^3.0.1                                    # Text fonts

  #Widgets
  cupertino_icons: ^1.0.2                                 # Cupertino icons
  flutter_svg: ^1.1.5                                     # Reading SVG images
  auto_size_text: ^3.0.0
  custom_sliding_segmented_control: ^1.7.2
  syncfusion_flutter_sliders: ^20.3.52

  # Local Database
  get_storage: ^2.0.3                                     # Store data locally

  #Helpers
  flutter_native_splash: ^2.2.10+1                        # Native Splash
  package_info_plus: ^2.0.0
  path_provider: ^2.0.11
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
